"""Constantes compartidas del nucleo.

Aqui viven los valores por defecto y limites usados en mas de un modulo.
Los valores configurables por el usuario pertenecen a config.yaml.
"""

DEFAULT_CAMERA_DEVICE_INDEX = 0
DEFAULT_FRAME_WIDTH = 640
DEFAULT_FRAME_HEIGHT = 480
DEFAULT_TARGET_FPS = 30

DEFAULT_HAND_MODEL_PATH = "models/hand_landmarker.task"
DEFAULT_MAX_HANDS = 2
DEFAULT_MIN_DETECTION_CONFIDENCE = 0.5
DEFAULT_MIN_PRESENCE_CONFIDENCE = 0.5
DEFAULT_MIN_TRACKING_CONFIDENCE = 0.5

DEFAULT_GESTURE_MODEL_PATH = "models/gesture_recognizer.task"
DEFAULT_STABILIZATION_FRAMES = 5
DEFAULT_RELEASE_FRAMES = 5
DEFAULT_MIN_GESTURE_CONFIDENCE = 0.5

ACTION_LOGGER_NAME = "recognizer.actions"
DEFAULT_ACTION_COOLDOWN_SECONDS = 1.0
DEFAULT_REPEAT_SECONDS = 0.0  # 0 = sin repeticion

CONTEXT_ENV_GESTURE = "RECOGNIZER_GESTURE"
CONTEXT_ENV_HANDEDNESS = "RECOGNIZER_HANDEDNESS"
CONTEXT_ENV_CONFIDENCE = "RECOGNIZER_CONFIDENCE"
CONTEXT_ENV_TIMESTAMP = "RECOGNIZER_TIMESTAMP"

HTTP_URL_PREFIX = "http://"
HTTPS_URL_PREFIX = "https://"
URL_PREFIXES = (HTTP_URL_PREFIX, HTTPS_URL_PREFIX)

POINTER_LOGGER_NAME = "recognizer.pointer"
POINTER_MAX_VISIBLE_HANDS = 1
DEFAULT_POINTER_ENABLED = True
DEFAULT_POINTER_ACTIVE_ZONE_MIN = 0.2
DEFAULT_POINTER_ACTIVE_ZONE_MAX = 0.8
DEFAULT_POINTER_MIRROR_X = True
DEFAULT_POINTER_SMOOTHING_ALPHA = 0.35
DEFAULT_THUMB_OPEN_THRESHOLD = 0.5

DEFAULT_SCROLL_LINES = 3
DEFAULT_SCROLL_REPEAT_SECONDS = 0.15
MIN_SCROLL_LINES = 1
SCROLL_FIXED_AXIS = 0

MIN_ANGLE_DEG = 0.0
MAX_ANGLE_DEG = 180.0
DEFAULT_RULE_STRAIGHT_ANGLE_DEG = 160.0
DEFAULT_RULE_DIRECTION_TOLERANCE_DEG = 30.0
RULE_CONFIDENCE = 1.0
MIN_VECTOR_NORM = 1e-9

MILLISECONDS_PER_SECOND = 1000
MIN_ELAPSED_SECONDS = 1e-9
MAX_CONSECUTIVE_READ_FAILURES = 30
FPS_LOG_INTERVAL = 30
ESC_KEY = 27
WINDOW_TOPMOST_ENABLED = 1
WINDOW_TOPMOST_DISABLED = 0
WINDOW_MIN_VISIBLE_VALUE = 1.0

PERSON_LABEL = "person"
DEFAULT_PEOPLE_MODEL_PATH = "models/yolo26n.pt"
DEFAULT_PEOPLE_CONFIDENCE = 0.5

DEFAULT_LINE_POSITION = 0.5
DEFAULT_LINE_CONFIRM_FRAMES = 2
DEFAULT_TRACKER_CONFIG = "bytetrack.yaml"

DEFAULT_INTRUSION_ZONE_X_MIN = 0.25
DEFAULT_INTRUSION_ZONE_Y_MIN = 0.4
DEFAULT_INTRUSION_ZONE_X_MAX = 0.75
DEFAULT_INTRUSION_ZONE_Y_MAX = 0.9
DEFAULT_INTRUSION_CONFIRM_FRAMES = 3
DEFAULT_INTRUSION_RELEASE_FRAMES = 5
DEFAULT_INTRUSION_ALERT_REPEAT_SECONDS = 2.0

DEFAULT_POSTURE_MODEL_PATH = "models/yolo26n-pose.pt"
DEFAULT_POSTURE_KEYPOINT_CONFIDENCE = 0.5
DEFAULT_POSTURE_MAX_HEAD_OFFSET_RATIO = 0.35
DEFAULT_POSTURE_MIN_HEAD_HEIGHT_RATIO = 0.4
DEFAULT_POSTURE_MAX_TORSO_ANGLE_DEG = 20.0
DEFAULT_POSTURE_MAX_SHOULDER_TILT_RATIO = 0.2
DEFAULT_POSTURE_CONFIRM_FRAMES = 5
DEFAULT_POSTURE_RELEASE_FRAMES = 10

DEFAULT_BROWSER_DEBUGGING_PORT: int = 9222
DEFAULT_CDP_CONNECT_TIMEOUT: float = 2.0
DEFAULT_CDP_COMMAND_TIMEOUT: float = 3.0
CDP_CHROME_LAUNCH_TIMEOUT: float = 5.0
CDP_POLL_INTERVAL: float = 0.5
