"""Constantes compartidas del nucleo.

Aqui viven los valores por defecto y limites usados en mas de un modulo.
Los valores configurables por el usuario pertenecen a config.yaml.
"""

DEFAULT_CAMERA_DEVICE_INDEX = 0
DEFAULT_FRAME_WIDTH = 640
DEFAULT_FRAME_HEIGHT = 480
DEFAULT_TARGET_FPS = 30

DEFAULT_HAND_MODEL_PATH = "models/hand_landmarker.task"
DEFAULT_MAX_HANDS = 2
DEFAULT_MIN_DETECTION_CONFIDENCE = 0.5
DEFAULT_MIN_PRESENCE_CONFIDENCE = 0.5
DEFAULT_MIN_TRACKING_CONFIDENCE = 0.5

DEFAULT_GESTURE_MODEL_PATH = "models/gesture_recognizer.task"
DEFAULT_STABILIZATION_FRAMES = 5
DEFAULT_RELEASE_FRAMES = 5
DEFAULT_MIN_GESTURE_CONFIDENCE = 0.5

ACTION_LOGGER_NAME = "recognizer.actions"
DEFAULT_ACTION_COOLDOWN_SECONDS = 1.0

MILLISECONDS_PER_SECOND = 1000
MIN_ELAPSED_SECONDS = 1e-9
MAX_CONSECUTIVE_READ_FAILURES = 30
FPS_LOG_INTERVAL = 30
ESC_KEY = 27
